# Generated by Django 5.0.1 on 2024-10-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topapp', '0002_alter_customuser_fk_cargo_alter_customuser_fk_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('fk_filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topapp.filial')),
                ('fk_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topapp.fornecedor')),
            ],
        ),
    ]
