# Generated by Django 5.0.1 on 2024-11-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topapp', '0003_fornecedor_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fk_cargo',
        ),
        migrations.AddField(
            model_name='produto',
            name='medida',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='rua',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='fk_filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topapp.filial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='fk_fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topapp.fornecedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=255)),
                ('quantidade_reservada', models.CharField(max_length=255)),
                ('fk_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.filial')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('fk_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.filial')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('medida', models.CharField(max_length=255)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.cliente')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.cliente')),
                ('fk_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.filial')),
                ('fk_produto_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.produtocliente')),
            ],
        ),
    ]
