# Generated by Django 5.0.1 on 2024-11-06 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topapp', '0005_remove_produto_fk_filial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='quantidade_reservada',
            new_name='tipomovimentacao',
        ),
        migrations.AddField(
            model_name='estoque',
            name='fk_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
