# Generated by Django 5.0.1 on 2024-11-17 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topapp', '0007_fornecedor_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='tipomovimentacao',
            new_name='quantidade_reservada',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='fk_usuario',
        ),
        migrations.AddField(
            model_name='produto',
            name='unidadeMedida',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=255)),
                ('tipomovimentacao', models.CharField(max_length=255)),
                ('fk_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.filial')),
                ('fk_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topapp.produto')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
