# Generated by Django 5.0.1 on 2024-11-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topapp', '0008_rename_tipomovimentacao_estoque_quantidade_reservada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
